### ISSUE TITLE
[DOC] Broken link to one example.

### ISSUE THREAD

**Issue by lazykyama** [rapidsai/notebooks-contrib#176]
## Report incorrect documentation

This is a trivial issue. Please fix it if needed.

**Location of incorrect documentation**
Second example of https://github.com/rapidsai/notebooks-contrib#intermediate-notebooks
"Dask_with_cuDF_and_XGBoost_Disk"

**Describe the problems or issues found in the documentation**
Now, the link URL is below but this is 404.
https://github.com/rapidsai/notebooks-contrib/blob/master/intermediate_notebooks/examples/Dask_with_cuDF_and_XGBoost_Disk.ipynb

**Steps taken to verify documentation is incorrect**
Only click the link...

**Suggested fix for documentation**
The URL should be
https://github.com/rapidsai/notebooks-contrib/blob/master/intermediate_notebooks/examples/Dask_with_cuDF_and_XGBoost_from_Disk.ipynb

The current file name is "Dask_with_cuDF_and_XGBoost_Disk.ipynb" but correct name should be "Dask_with_cuDF_and_XGBoost_ **from_** Disk.ipynb".

**Comment by taureandyernv** [comment]
Hey @lazykyama, we updated the links in a recent readme update, and this notebook was retired (removed form the readme).  we're deciding on whether or not to have archived notebooks.  Thanks for the heads up though!
