### ISSUE TITLE
[BUG] JIT compliation error in PLAsTiCC notebook 

### ISSUE THREAD

**Issue by bigwater** [rapidsai/notebooks-contrib#179]
**Describe the bug**
I am looking at the plasticc notebook that is located in notebookscontrib/competition_notebooks/kaggle/plasticc/

In etl_gpu(df,df_meta) function, an error raised in df['flux_ratio_sq'] = df['flux_ratio_sq'].applymap(lambda x: math.pow(x,2)). Seems the JIT did no compile the lambda expression. 

 JIT compile log for

(20): error: identifier "_ZN8__main__7etl_gpu12_3clocals_3e17_3clambda_3e_2423Ef_param_0" is undefined

(20): error: an asm operand must have scalar type

(23): error: identifier "_ZN8__main__7etl_gpu12_3clocals_3e17_3clambda_3e_2423Ef_param_1" is undefined

(23): error: an asm operand must have scalar type

(86): error: identifier "retval0_0" is undefined

(86): error: an asm operand must have scalar type

6 errors detected in this compilation.

However, if changing the line to df['flux_ratio_sq'] = df['flux_ratio_sq'] * df['flux_ratio_sq'], everything runs normally. 

**Steps/Code to reproduce bug**
Run notebookscontrib/competition_notebooks/kaggle/plasticc notebook. Modify groupby_aggs(df,aggs,col) function as the follows to avoid a key error in cudf 0.9. 

def groupby_aggs(df,aggs,col):
    res = None
    for i,j in aggs.items():
        for k in j:
            tmp = df.groupby(col,as_index=False).agg({i:[k]})
            tmp.columns = [tmp.columns[0], k+"_"+tmp.columns[1]]
            if res is None:
                res = tmp
            else:
                res = res.merge(tmp,on=[col],how='left')
        df.drop_column(i)
    return res 

The error raised in the **ETL part2 with 9x ~ 12x speedup** cell, where etl_gpu is called. 

**Expected behavior**

**Environment details (please complete the following information):**
I am using conda to install RAPIDS. I use a bare-metal environment. The GPU is a Tesla V100. 

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
arrow-cpp                 0.14.1           py37h6b969ab_1    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                    openblas
bleach                    3.1.0                      py_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cudatoolkit               9.2                           0    anaconda
cudf                      0.9.0                    py37_0    rapidsai
cugraph                   0.9.0                    py37_0    rapidsai
cuml                      0.9.1            cuda9.2_py37_0    rapidsai
cython                    0.29.13          py37he1b5a44_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
dlpack                    0.2                  he1b5a44_0    conda-forge
double-conversion         3.1.5                he1b5a44_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
fastavro                  0.22.4           py37h516909a_0    conda-forge
gflags                    2.2.2             he1b5a44_1001    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
joblib                    0.13.2                   py37_0
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                1.1.3                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcudf                   0.9.0                 cuda9.2_0    rapidsai
libcugraph                0.9.0                 cuda9.2_0    rapidsai
libcuml                   0.9.1                 cuda9.2_0    rapidsai
libedit                   3.1.20181209         hc058e9b_0
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
liblapack                 3.8.0               12_openblas    conda-forge
libnvstrings              0.9.0                 cuda9.2_0    rapidsai
libopenblas               0.3.7                h6e990d7_1    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.9.0                 cuda9.2_0    rapidsai
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
llvmlite                  0.29.0           py37hf484d3e_0    numba
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nccl                      2.4.6.1               cuda9.2_0    nvidia
ncurses                   6.1                  he6710b0_1
notebook                  6.0.1                    py37_0    conda-forge
numba                     0.45.1          np116py37hf484d3e_0    numba
numpy                     1.16.4           py37h95a1406_0    conda-forge
nvstrings                 0.9.0                    py37_0    rapidsai
openssl                   1.1.1c               h516909a_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.5.1                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.2.2                   py37_0
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyarrow                   0.14.1           py37h8b68381_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyrsistent                0.15.4           py37h516909a_0    conda-forge
python                    3.7.4                h265db76_1    anaconda
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyzmq                     18.0.2           py37h1768529_2    conda-forge
re2                       2019.09.01           he1b5a44_0    conda-forge
readline                  7.0                  h7b6447c_5
rmm                       0.9.0                    py37_0    rapidsai
scikit-learn              0.21.2           py37h22eb022_0
scipy                     1.3.1            py37he2b7bc3_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sqlite                    3.29.0               h7b6447c_0
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.8                hbc83047_0
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py37_0
xz                        5.2.4                h14c3975_4
zeromq                    4.3.2                he1b5a44_2    conda-forge
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.0                h3b9ef0a_0    conda-forge

**Addition Comments**
Am I missing something? Could anything lead me to the reason how I could use **applymap** function in a cudf Series? 

Thank you.

**Comment by chi2liu** [comment]
do you fix it? 
I meet this problem too

**Comment by taureandyernv** [comment]
@chi2liu and @bigwater, we have both archived the original Plasticc notebook and updated it for 0.9+ here: https://github.com/rapidsai/notebooks-contrib/tree/master/conference_notebooks/KDD_2019/plasticc.  I'm going to close this issue, but please reopen it if you still require assistance!
