### ISSUE TITLE
Old Colab Install Script Still In Use on Default "Try RAPIDS" [BUG]

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/notebooks-contrib#182]
**Describe the bug**
Colab install script on [rapids-colab.ipynb](https://rapids-goai.slack.com/archives/C5E06F4DC/p1568777822007900) ("Launch in Colab" notebook found at [rapids.ai/start](https://rapids.ai/start.html)) has not been updated to #159 

**Steps/Code to reproduce bug**
1. Visit [rapids.ai](https://rapids.ai)
2. Click "Get Started"
3. Click "Launch in Colab"
4. See [cell #5](https://colab.research.google.com/drive/1XTKHiIcvyL5nuldx0HSL_dUa8yopzy_Y#scrollTo=m0jdXBRiDSzj&line=4&uniqifier=1)

**Expected behavior**
```
!wget -nc https://raw.githubusercontent.com/rapidsai/notebooks-contrib/master/utils/rapids-colab.sh
!bash rapids-colab.sh 

import sys, os

sys.path.append('/usr/local/lib/python3.6/site-packages/')
os.environ['NUMBAPRO_NVVM'] = '/usr/local/cuda/nvvm/lib64/libnvvm.so'
os.environ['NUMBAPRO_LIBDEVICE'] = '/usr/local/cuda/nvvm/libdevice/'
```

**Environment details (please complete the following information):**
 - Environment location: Google Colab
 - Method of RAPIDS libraries install: Conda

**Additional context**
Not able to find where/if this notebook is stored as a file. May be worth adding to `/colab_notebooks` so it can be updated with other Colab notebooks?

**Comment by UmashankarTriforce** [comment]
I wish to work on this issue. The question that I have is - 
1. If we maintain `rapids-colab.ipynb` under `/colab_notebooks`, how do we link this file to Colabs? 
2. Even if we manage to link it, will it be automatically updated as we update the file here in repo?

**Comment by taureandyernv** [comment]
@gumdropsteve thanks!  The good news is that this is a known and fixed issue, however we are waiting for site staging staging to get merged into the site master.  Also, this notebook will be getting updates so that you can try out more of RAPIDS in it.  Once that is finalized, we'll bring it into `/colab_notebooks`

**Comment by taureandyernv** [comment]
closing because the updated staging code was pushed for v0.10
