### ISSUE TITLE
Google_Colab doesn't allocate Tesla T4, but only Tesla K80

### ISSUE THREAD

**Issue by egkiastas** [rapidsai/notebooks-contrib#208]
### After many resets on runtimes, colab continues to give me a Tesla K80 GPU instance.
I tried to setup and install RAPIDS Libraries with other ways but I understood that Tesla T4 is prerequisite for cudf and other packages to be imported and recognized to run even simple examples. What is the problem?

```
Fri Oct 11 14:00:43 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P8    35W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

**Comment by gumdropsteve** [comment]
Hey @egkiastas, this has been a growing issue over the past month or so and a bunch of people have been talking about it in the [Slack](https://rapids-goai.slack.com/join/shared_invite/enQtMjE0Njg5NDQ1MDQxLTJiN2FkNTFkYmQ2YjY1OGI4NTc5Y2NlODQ3ZDdiODEwYmRiNTFhMzNlNTU5ZWJhZjA3NTg4NDZkMThkNTkxMGQ). To the best of my knowledge (a few days lagged), nobody knows why, or how to fix it, yet.

**Comment by taureandyernv** [comment]
@egkiastas , this has become our #1 reported issue, and in the background we've been trying improve the experience in as many avenues as we can.  We know why (Colab uses spare T4s and they just don't have any spares compared to the K80s).  We have promoted Colab as the cheapest "try it out" avenue, but there exists "not as cheap as 'free'" alternatives that you can quickly try with a more powerful GPU and far less frustration for your workflows (like waiting to have RAPIDS installed every time to run a short example workflow).  We have images that you can quickly deploy on several cloud providers, on far beefier/frustration free instances, for about the cost of a cup of coffee per hour and have per second billing.  It is the fastest way to try out RAPIDS (even faster than Colab).  You can also use any modern NVIDIA GPU (Pascal based -1xxx series or newer GPU) on a system set up properly to try RAPIDS.  We suggest you try either avenue to get the best experience.

**Comment by egkiastas** [comment]
@gumdropsteve  @taureandyernv Thank you for your answers. I have created a g4 instance on EC2 and I run the images and the examples there.

**Comment by taureandyernv** [comment]
@egkiastas, Colab now has P100 instances and we have updated our script with PR #226.  We see you get a P100 16%-25% of the time if you keep trying.  Hooray!
