### ISSUE TITLE
[BUG] Need to change parent module name of `concat` and a pre-process step has an error.

### ISSUE THREAD

**Issue by lazykyama** [rapidsai/notebooks-contrib#224]
**Describe the bug**

Sorry in advance if this issue (and/or related issues) has been already reported.

"blog_notebooks/cyber/network_mapping/lanl_network_mapping_using_rapids.ipynb" example has 2 issues.

First is similar to commit 279c7b0220c24bab84105e68fc23c1051816c1b9. In `flow_classification`, previous function call, `cudf.multi.concat()`, has been already changed to `cudf.concat()`. In `network_mapping`, this change hasn't been applied. We need to apply this change before trying this `network_mapping` example.

However, after applying this, I'm facing another issue. When using one dataset, `wls_day-02.bz2`, from https://csr.lanl.gov/data/2017.html, `ValueError: All series must be of same type` occurs. The detail stacktrace is below.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-43468c9f8d3b> in <module>
     18 
     19 parts = [dask.delayed(pipeline)(x, EVENT_CODES_OF_INTEREST, REGEX_MAPPINGS) for x in logs_gddf.to_delayed()]
---> 20 temp_df = dask_cudf.from_delayed(parts)
     21 # Bring data back to a single GPU, for downstream graph analytics
     22 auth_gdf = temp_df.compute()

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/dataframe/io/io.py in from_delayed(dfs, meta, divisions, prefix, verify_meta)
    561 
    562     if meta is None:
--> 563         meta = delayed(make_meta)(dfs[0]).compute()
    564     else:
    565         meta = make_meta(meta)

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     78         get_id=_thread_get_id,
     79         pack_exception=pack_exception,
---> 80         **kwargs
     81     )
     82 

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

/opt/conda/envs/rapids/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

<ipython-input-5-13620ccc67b0> in pipeline(df, event_codes, regex_mappings, clean)
     17 
     18     # recombine the processed output
---> 19     out_df = cudf.concat(out_dfs)
     20     return out_df
     21 

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/reshape.py in concat(objs, axis, ignore_index, sort)
     74 
     75     if typ is DataFrame:
---> 76         return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
     77     elif typ is Series:
     78         return Series._concat(objs, axis=axis)

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/dataframe.py in _concat(cls, objs, axis, ignore_index)
   1748                 ),
   1749             )
-> 1750             for c in unique_columns_ordered_ls
   1751         ]
   1752         out = cls(data)

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/dataframe.py in <listcomp>(.0)
   1748                 ),
   1749             )
-> 1750             for c in unique_columns_ordered_ls
   1751         ]
   1752         out = cls(data)

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/series.py in _concat(cls, objs, axis, index)
   1105         else:
   1106             name = None
-> 1107         col = Column._concat([o._column for o in objs])
   1108         return cls(data=col, index=index, name=name)
   1109 

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/column/column.py in _concat(cls, objs, dtype)
    119         for obj in objs:
    120             if not (obj.is_type_equivalent(head)):
--> 121                 raise ValueError("All series must be of same type")
    122 
    123         # Handle strings separately

ValueError: All series must be of same type
```

**Steps/Code to reproduce bug**

* Download `wls_day-02.bz2`, from https://csr.lanl.gov/data/2017.html.
    - And, uncompress this file.
* Start a RAPIDS docker container by following below section.
* Clone this repo.
* Move to the directory `blog_notebooks/cyber/network_mapping`.
* Open a notebook, `lanl_network_mapping_using_rapids.ipynb`.
* Change `cudf.multi.concat` to `cudf.concat` and `AUTH_INPUT_PATH = '../../../data/input/lanl/wls.csv'` to `AUTH_INPUT_PATH = '/path/to/data/wls_day-02.csv'`.
* Run all cells except for a cell having `!mkdir -p ../../../data/input/lanl` line.

**Expected behavior**

No errors occur.

**Environment details (please complete the following information):**
 - Local machine: Ubuntu18.04 with TITAN X (Pascal)
 - Method of RAPIDS libraries install: [~conda~, Docker, ~or from source~]
   - Command: `sudo nvidia-docker run --rm -it -v $(pwd):/ws -v /path/to/data/:/data -p 8888:8888 nvcr.io/nvidia/rapidsai/rapidsai:0.10-cuda10.1-runtime-ubuntu18.04` 

**Additional context**

IMHO, this error happens due to inconsistent behavior about empty columns type.

**Comment by datametrician** [comment]
@BartleyR @taureandyernv would you triage please?

**Comment by BartleyR** [comment]
@efajardo-nv @brhodes10 This does look like to me the empty types. I tried it on a smaller subset of data and it worked, but this can be replicated. I believe we ran into a similar error recently. 

Also, we can likely move this into the CLX repo now as a different network mapping notebooks.

@lazykyama - if you’re just interested in the network mapping part of the code and not the parsing portion of it, we do have a similar notebook (same idea, different dataset) that you can look at in the interim here: https://github.com/rapidsai/clx/tree/branch-0.11/notebooks/network_mapping .

**Comment by taureandyernv** [comment]
Thanks @BartleyR  for checking this out.  @lazykyama , thanks for helping the community and reporting this!
 
While I inadvertently addressed this a portion of your findings in PR #223 (the removing multi), I have also assigned @thomcom to help fix anything lingering.

**Comment by lazykyama** [comment]
@BartleyR Thanks for checking this and sharing new example notebook! I'll check and try it.

@taureandyernv Thanks for your helping to fix this!

**Comment by thomcom** [comment]
Thanks for working with us @lazykyama ! I've pushed a set of fixes for this notebook, as a few things have changed in `cudf` since this notebook was originally written.

https://github.com/rapidsai/notebooks-contrib/pull/237
