### ISSUE TITLE
[BUG]08_introduction_to_Dask_XGBoost notebook fails with TypeError

### ISSUE THREAD

**Issue by mfeiman** [rapidsai/notebooks-contrib#280]
**Describe the bug**

I'm trying to run the  
notebooks-contrib/getting_started_notebooks/intro_tutorials/08_Introduction_to_Dask_XGBoost.ipynb
- completely unchanged.

**Steps/Code to reproduce bug**

The Notebook cells runs successfully till it come to "Train Model" cells
and when executing cell with code:
bst = dask_xgboost.train(client, params, X_train_dask_cudf, y_train_dask_cudf, num_boost_round=num_round)
- this cell fails
  
** Error message **
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/dask_xgboost/core.py in train(client, params, data, labels, dmatrix_kwargs, **kwargs)
    189     """
    190     return client.sync(_train, client, params, data,
--> 191                        labels, dmatrix_kwargs, **kwargs)
    192 
    193 

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    751         else:
    752             return sync(
--> 753                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    754             )
    755 

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    335             e.wait(10)
    336     if error[0]:
--> 337         six.reraise(*error[0])
    338     else:
    339         return result[0]

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/distributed/utils.py in f()
    320             if callback_timeout is not None:
    321                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 322             result[0] = yield future
    323         except Exception as exc:
    324             error[0] = sys.exc_info()

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/tornado/gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/tornado/gen.py in run(self)
    734                     if exc_info is not None:
    735                         try:
--> 736                             yielded = self.gen.throw(*exc_info)  # type: ignore
    737                         finally:
    738                             # Break up a reference to itself

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/dask_xgboost/core.py in _train(client, params, data, labels, dmatrix_kwargs, **kwargs)
    151 
    152     # Get the results, only one will be non-None
--> 153     results = yield client._gather(futures)
    154     result = [v for v in results if v][0]
    155     num_class = params.get("num_class")

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/tornado/gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1666                             exc = CancelledError(key)
   1667                         else:
-> 1668                             six.reraise(type(exception), exception, traceback)
   1669                         raise exc
   1670                     if errors == "skip":

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/dask_xgboost/core.py in train_part()
     75     """
     76     data, labels = zip(*list_of_parts)  # Prepare data
---> 77     data = concat(data)                 # Concatenate many parts into one
     78     labels = concat(labels)
     79     if dmatrix_kwargs is None:

/opt/ibm/spectrumcomputing/anaconda2019/anaconda/envs/gpuenv/lib/python3.7/site-packages/dask_xgboost/core.py in concat()
     60     else:
     61         raise TypeError("Data must be either numpy arrays or pandas dataframes"
---> 62                         ". Got %s" % type(L[0]))
     63 
     64 

**TypeError**: **_Data must be either numpy arrays or pandas dataframes. Got <class 'cudf.dataframe.dataframe.DataFrame'>_**

**Environment details:**

The Notebook runs on Power host with 4 GPUs

The LocalCUDACluster is created and shows:
ClusterWorkers: 4
Cores: 4
Memory: 544.35 GB

All Python packages installed using IBM Conda channel:
https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda

This is the packages installed as shown in the Notebook:
cuDF Version: 0.9.0
Dask Version: 2.3.0
Dask cuDF Version: 0.9.0
Dask XGBoost Version: 0.1.7
numpy Version: 1.16.5
pandas Version: 0.24.2
Scikit-Learn Version: 0.21.3

**Comment by rnyak** [comment]
@mfeiman do you still have the issue? I recommend to use latest rapids version (0.14 nightly) either in a conda env, or docker container.

you can use this code snippet for new dask-xgb API:

```
....
dtrain = xgb.dask.DaskDMatrix(client, X_train, Y_train)
%%time

bst= xgb.dask.train(client,
                        {
                         'learning_rate': 0.3,
                          'max_depth': 8,
                          'objective': 'reg:squarederror',
                          'subsample': 0.6,
                          'gamma': 1,
                          'silent': True,
                          'verbose_eval': True,
                          'tree_method':'gpu_hist',
                          'n_gpus': 1
                        },
                        dtrain,
                        num_boost_round=100, evals=[(dtrain, 'train')])

# generate predictions on the test set
'''feed X_test as a dask.dataframe'''
prediction = xgb.dask.predict(client, trained_model['booster'], X_test).persist()

wait(prediction)

prediction.head()

```
Hope that helps.

**Comment by mfeiman** [comment]
@rnyak thank you! Actually I got updated dask-xgboost 0.1.9  build on Power (and dependencies) - with that  worked. The dask-xgboost version is so far only in daily build on Power  (c 1.7.1a) but since it works I will close the issue now. Thanks again!
