### ISSUE TITLE
scikit-learn PCA is not parallel. Get rid of multiprocessing cell, it just confuses users

### ISSUE THREAD

**Issue by pklemenkov** [rapidsai/notebooks-contrib#30]

**Comment by pklemenkov** [comment]
`import multiprocessing`
`print(multiprocessing.cpu_count()) # Return the number of CPUs in the system.`

This cell is useless and confusing because PCA in scikit-learn has no parallel implementation

**Comment by UmashankarTriforce** [comment]
Is this issue still open? I would like to work on this!
